const EDITION_ABI = [
  {
    type: "function",
    name: "mint",
    stateMutability: "payable",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "quantity", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "createEdition",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "config",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "uri", type: "string" },
          { name: "tokenId", type: "uint256" },
          { name: "maxSupply", type: "uint256" },
          { name: "mintPrice", type: "uint256" },
          { name: "mintStart", type: "uint256" },
          { name: "mintEnd", type: "uint256" },
          { name: "walletLimit", type: "uint256" },
          { name: "royaltyBps", type: "uint96" },
          { name: "royaltyReceiver", type: "address" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "closeEdition",
    stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMinter",
    stateMutability: "nonpayable",
    inputs: [{ name: "minter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "pause",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "unpause",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "editionConfig",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "uri", type: "string" },
          { name: "tokenId", type: "uint256" },
          { name: "maxSupply", type: "uint256" },
          { name: "mintPrice", type: "uint256" },
          { name: "mintStart", type: "uint256" },
          { name: "mintEnd", type: "uint256" },
          { name: "walletLimit", type: "uint256" },
          { name: "royaltyBps", type: "uint96" },
          { name: "royaltyReceiver", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "totalMinted",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "walletMints",
    stateMutability: "view",
    inputs: [
      { name: "wallet", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isEditionOpen",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getAllEditionIds",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "uri",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "setApprovalForAll",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operator", type: "address" },
      { name: "approved", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "isApprovedForAll",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "operator", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [
      { name: "account", type: "address" },
      { name: "id", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "EditionMinted",
    anonymous: false,
    inputs: [
      { indexed: true, name: "to", type: "address" },
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: false, name: "quantity", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "EditionCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: false, name: "uri", type: "string" },
      { indexed: false, name: "maxSupply", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "EditionClosed",
    anonymous: false,
    inputs: [{ indexed: true, name: "tokenId", type: "uint256" }],
  },
  {
    type: "event",
    name: "MinterSet",
    anonymous: false,
    inputs: [{ indexed: true, name: "minter", type: "address" }],
  },
  {
    type: "event",
    name: "Withdrawn",
    anonymous: false,
    inputs: [
      { indexed: true, name: "to", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
] as const;

export default EDITION_ABI;
