const FACTORY_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "feeManager_", type: "address", internalType: "address" },
      { name: "fixedPriceMinter_", type: "address", internalType: "address" },
      { name: "freeMinter_", type: "address", internalType: "address" },
      { name: "timedMinter_", type: "address", internalType: "address" },
      { name: "allowlistMinter_", type: "address", internalType: "address" },
      { name: "owner_", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "error", name: "DeploymentFailed", inputs: [] },
  { type: "error", name: "InvalidMinterType", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  {
    type: "event",
    name: "NFTDropDeployed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "collection", type: "address" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: true, name: "minter", type: "address" },
      { indexed: false, name: "minterType", type: "uint8" },
      { indexed: false, name: "name", type: "string" },
    ],
  },
  {
    type: "event",
    name: "EditionDeployed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "collection", type: "address" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: true, name: "minter", type: "address" },
      { indexed: false, name: "minterType", type: "uint8" },
      { indexed: false, name: "name", type: "string" },
    ],
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    anonymous: false,
    inputs: [
      { indexed: true, name: "previousOwner", type: "address" },
      { indexed: true, name: "newOwner", type: "address" },
    ],
  },
  {
    type: "function",
    name: "deployNFTDrop",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "nftConfig",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "baseURI", type: "string" },
          { name: "hiddenURI", type: "string" },
          { name: "maxSupply", type: "uint256" },
          { name: "mintPrice", type: "uint256" },
          { name: "mintStart", type: "uint256" },
          { name: "mintEnd", type: "uint256" },
          { name: "walletLimit", type: "uint256" },
          { name: "royaltyBps", type: "uint96" },
          { name: "royaltyReceiver", type: "address" },
          { name: "isRevealed", type: "bool" },
        ],
      },
      { name: "minterType", type: "uint8" },
      { name: "minterData", type: "bytes" },
    ],
    outputs: [{ name: "collection", type: "address" }],
  },
  {
    type: "function",
    name: "deployEdition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      {
        name: "firstEdition",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "uri", type: "string" },
          { name: "tokenId", type: "uint256" },
          { name: "maxSupply", type: "uint256" },
          { name: "mintPrice", type: "uint256" },
          { name: "mintStart", type: "uint256" },
          { name: "mintEnd", type: "uint256" },
          { name: "walletLimit", type: "uint256" },
          { name: "royaltyBps", type: "uint96" },
          { name: "royaltyReceiver", type: "address" },
        ],
      },
      { name: "minterType", type: "uint8" },
      { name: "minterData", type: "bytes" },
    ],
    outputs: [{ name: "collection", type: "address" }],
  },
  {
    type: "function",
    name: "getCollection",
    stateMutability: "view",
    inputs: [{ name: "collection", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "contractAddress", type: "address" },
          { name: "creator", type: "address" },
          { name: "minter", type: "address" },
          { name: "tokenType", type: "uint8" },
          { name: "minterType", type: "uint8" },
          { name: "deployedAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getCreatorCollections",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "function",
    name: "getAllCollections",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "contractAddress", type: "address" },
          { name: "creator", type: "address" },
          { name: "minter", type: "address" },
          { name: "tokenType", type: "uint8" },
          { name: "minterType", type: "uint8" },
          { name: "deployedAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getTotalCollections",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "transferOwnership",
    stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "feeManager",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "fixedPriceMinter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "freeMinter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "timedMinter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "allowlistMinter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "updateFeeManager",
    stateMutability: "nonpayable",
    inputs: [{ name: "feeManager_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateFixedPriceMinter",
    stateMutability: "nonpayable",
    inputs: [{ name: "minter_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateFreeMinter",
    stateMutability: "nonpayable",
    inputs: [{ name: "minter_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTimedMinter",
    stateMutability: "nonpayable",
    inputs: [{ name: "minter_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateAllowlistMinter",
    stateMutability: "nonpayable",
    inputs: [{ name: "minter_", type: "address" }],
    outputs: [],
  },
] as const;

export default FACTORY_ABI;