const KALIESO_POSTS_ABI = [
  {
    type: "function",
    name: "createPost",
    stateMutability: "nonpayable",
    inputs: [
      { name: "nftContract", type: "address" },
      { name: "tokenType", type: "uint8" },
      { name: "editionTokenId", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "contentURI", type: "string" },
      { name: "mediaType", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deletePost",
    stateMutability: "nonpayable",
    inputs: [{ name: "postId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "addComment",
    stateMutability: "nonpayable",
    inputs: [
      { name: "postId", type: "uint256" },
      { name: "content", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deleteComment",
    stateMutability: "nonpayable",
    inputs: [
      { name: "postId", type: "uint256" },
      { name: "commentId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "likePost",
    stateMutability: "nonpayable",
    inputs: [{ name: "postId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "unlikePost",
    stateMutability: "nonpayable",
    inputs: [{ name: "postId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getPost",
    stateMutability: "view",
    inputs: [{ name: "postId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "postId", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "nftContract", type: "address" },
          { name: "tokenType", type: "uint8" },
          { name: "editionTokenId", type: "uint256" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "contentURI", type: "string" },
          { name: "mediaType", type: "string" },
          { name: "likeCount", type: "uint256" },
          { name: "commentCount", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "deleted", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getPostsByCreator",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "postId", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "nftContract", type: "address" },
          { name: "tokenType", type: "uint8" },
          { name: "editionTokenId", type: "uint256" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "contentURI", type: "string" },
          { name: "mediaType", type: "string" },
          { name: "likeCount", type: "uint256" },
          { name: "commentCount", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "deleted", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getPostByNFTContract",
    stateMutability: "view",
    inputs: [{ name: "nftContract", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "postId", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "nftContract", type: "address" },
          { name: "tokenType", type: "uint8" },
          { name: "editionTokenId", type: "uint256" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "contentURI", type: "string" },
          { name: "mediaType", type: "string" },
          { name: "likeCount", type: "uint256" },
          { name: "commentCount", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "deleted", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getComments",
    stateMutability: "view",
    inputs: [{ name: "postId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "commentId", type: "uint256" },
          { name: "postId", type: "uint256" },
          { name: "commenter", type: "address" },
          { name: "content", type: "string" },
          { name: "createdAt", type: "uint256" },
          { name: "deleted", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "hasLiked",
    stateMutability: "view",
    inputs: [
      { name: "postId", type: "uint256" },
      { name: "wallet", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "totalPosts",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getPostIdByNFT",
    stateMutability: "view",
    inputs: [{ name: "nftContract", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "PostCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "postId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: true, name: "nftContract", type: "address" },
      { indexed: false, name: "tokenType", type: "uint8" },
      { indexed: false, name: "title", type: "string" },
      { indexed: false, name: "createdAt", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PostDeleted",
    anonymous: false,
    inputs: [
      { indexed: true, name: "postId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
    ],
  },
  {
    type: "event",
    name: "CommentAdded",
    anonymous: false,
    inputs: [
      { indexed: true, name: "postId", type: "uint256" },
      { indexed: true, name: "commentId", type: "uint256" },
      { indexed: true, name: "commenter", type: "address" },
      { indexed: false, name: "content", type: "string" },
    ],
  },
  {
    type: "event",
    name: "CommentDeleted",
    anonymous: false,
    inputs: [
      { indexed: true, name: "postId", type: "uint256" },
      { indexed: true, name: "commentId", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PostLiked",
    anonymous: false,
    inputs: [
      { indexed: true, name: "postId", type: "uint256" },
      { indexed: true, name: "liker", type: "address" },
    ],
  },
  {
    type: "event",
    name: "PostUnliked",
    anonymous: false,
    inputs: [
      { indexed: true, name: "postId", type: "uint256" },
      { indexed: true, name: "liker", type: "address" },
    ],
  },
] as const;

export default KALIESO_POSTS_ABI;
